### ISSUE TITLE
Create classes 

### ISSUE THREAD

**Issue by yarelismartin** [alexberka/Rare-Server#1]
Create the following classes 
- [ ] Post
![image](https://github.com/user-attachments/assets/9572ab14-6b6e-4648-900e-3bc4a7d3dc15)

- [x] Categories 
![image](https://github.com/user-attachments/assets/1c82c988-7977-4221-a926-03ca08156a65)

- [ ] Tags
![image](https://github.com/user-attachments/assets/9c8a93e0-8fb3-43b3-a94f-e9bb7ec8db93)

- [x] User
![image](https://github.com/user-attachments/assets/413d899a-575b-4abb-8244-e0029edea577)

**Comment by alexberka** [comment]
Closed with #8 #9 #10 #11
Post Tags for stretch
